SELECT * FROM FORMATS;

SELECT * FROM PROJECT_STATUS;

SELECT * FROM PROJECTS;

SELECT * FROM COST_CENTER_SUMMARY_T

SELECT TERMINATION_INDICATOR, COUNT(PROJECT) FROM PROJECTS GROUP BY TERMINATION_INDICATOR;
SELECT STATUS, COUNT(*) FROM IDEAS GROUP BY STATUS;
SELECT STATUS, COUNT(*) FROM PROPOSALS GROUP BY STATUS;

SELECT DONOR_REPLY FROM PROPOSALS WHERE DONOR_REPLY IS NOT NULL;

SELECT --* 
PROJECT, ZONE
FROM AGRO_ECOZONE_PROJECTS AP, AGRO_ECOZONE A
WHERE A.ZONE_ID=AP.ZONE_ID

SELECT * 
--PROJECT, ZONE
FROM KEYWORDS K, KEYWORD_PROJECTS KP
WHERE KP.KWCODE=K.KWCODE

SELECT * FROM CROPS

SELECT PROJECT, 'CROP:' || CROP AS TAG FROM PROJECT_CROPS
SELECT PROJECT, TITLE AS TAG FROM PROJECT_DISCIPLINES

SELECT RESEARCH_ID, RESEARCH FROM RESEARCH_CATEGORY
SELECT PR.PROJECT, R.RESEARCH AS TAG, PR.PERCENTAGE FROM PROJECT_RESEARCH_CATEGORY PR, RESEARCH_CATEGORY R
WHERE PR.RESEARCH_ID=R.RESEARCH_ID

SELECT PROJECT, TITLE AS TAG FROM PROJECT_TOPICS

SELECT PROJECT, 'TYPE:' || PROJ_TYPE AS TAG, NULL AS PERCENTAGE FROM PROJECTS

SELECT PROJECT, 'CGIAR:' || PRIORITY AS TAG, PERCENTAGE FROM PROJECTS_CGIAR_PRIORITIES

SELECT PROJECT, 'MTP:' || MTP_PROJECT AS TAG, PERCENTAGE FROM PROJECTS_MTP

SELECT RESEARCH_LOC, REGION, COUNTRY FROM RESEARCH_LOC
SELECT RP.PROJECT, R.REGION AS TAG, NULL AS PERCENTAGE FROM RESEARCH_LOC_PROJECTS RP, RESEARCH_LOC R
WHERE RP.RESEARCH_LOC=R.RESEARCH_LOC

SELECT RP.PROJECT, 'COUNTRY:' || R.COUNTRY AS TAG, NULL AS PERCENTAGE FROM RESEARCH_LOC_PROJECTS RP, RESEARCH_LOC R
WHERE RP.RESEARCH_LOC=R.RESEARCH_LOC AND R.COUNTRY<>'*Region Only*'

SELECT * FROM AGREEMENTS_MEMBER WHERE AGREEMENT='AG-001291'
SELECT * FROM DONORS WHERE DONOR='SAA'

SELECT
  MEMBER, TYPE, AGREEMENT, WHOM_DONOR as DONOR, WHOM_PARTNER as PARTNER, 'PARTNER' as typePartner, 'DONOR' as typeDonor, 0 as version, 'PROMIS' as createdBy, 'PROMIS' as lastUpdatedBy
FROM AGREEMENTS_MEMBER WHERE WHOM_DONOR='SAA'

SELECT * FROM DONORS WHERE DONOR='SAA'